name: Deploy-To-Firebase

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.20.4
      uses: actions/setup-node@v1
      with:
        node-version: 18.20.4
    - name: Install dependencies
      run: npm install
    - name: Set API Key
      run: |
        echo "export const environment = { weatherToken: '${{ secrets.API_KEY }}' };" > src/environments/environment.ts
    - name: Set PROD API Key
      run: |
        echo "export const environment = { weatherToken: '${{ secrets.API_KEY }}' };" > src/environments/environment.prod.ts
    - name: Build
      run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
